[package]
name = "blackjack_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "blackjack_rs"

crate-type = ["cdylib", "rlib"]

[dependencies]
game_pieces_rs = { git = "https://github.com/NickyNocerino/game_pieces_rs.git" }
pyo3 = { version = "0.23.5", features = ["extension-module"] }
